### ISSUE TITLE
Nytt cmd ”music-cli fsm graph”

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#11]
Efter att ha haft en lång rad med buggar i mina fsm-beskrivningar och en anna rad med buggar i mina mermaid-grafer så kom jag plötsligt på att det ju vore enkelt att automatgenerera mermaidgraferna ur fsm-strukturen...

Då får vi automatiskt grafer som faktiskt beskriver hur resp process är implementerad, och det kan ju användas både för dokumentation och debugging.

**Comment by johanix** [comment]
This has been implemented.
