### ISSUE TITLE
Syncing the NS rrset is in join_wait_ds this is confusing.

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#141]
The syncing of the NSrrset is "hidden" in the join_wait_ds code.  This makes it difficult to find and follow what is happening.

**Comment by johanix** [comment]
This is important. Should probably break up this step into two steps.

**Comment by romu42** [comment]
I changed the name of the process to ns_synced to clarify the situaiton. Wait_ds is the precondition for Syncing the NS RRSET.
