### ISSUE TITLE
A blocked zone transition doesn't always stop when it should.  

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#143]
There seem to be situations where the code will get an error, but will still keep on going through the processes.  
ex: 
```
msat1.catch22.se.: Unable to update signer1 with new DNSKEYs map[signer1:[msat1.catch22.se. 300     IN      DNSKEY  256 3 13 Hmva5+2gzldmznimU5dYnIKYUHAwmROXhrqcxS33eiE2VEnWDJWCrwjjTVxtPzQzcrEXUm4qfx+AqCZR1zVQdw== msat1.catch22.se.       300     IN      DNSKEY  257 3 13 oVlyvr3PcPsLxLnMYcsUrvOQ+fQOoqgT927RUB4Sk0Sc7MG3D14/QBvA3k7+I1G2ho2oUU5LIkt1PZmaOZAOkQ==] signer2:[msat1.catch22.se.     300     IN      DNSKEY  256 3 13 RE+ZLtQrPODfcIg1DhpXFj3bZY5+uFqq26UqCoEIWOD5yNv8D7e3s5UYFqtb6rEc58YV/pR3viXcwBXL6YqTVw== msat1.catch22.se.       300     IN      DNSKEY  257 3 13 H+rUfGFYgJVsWqOSCOFs5Qy2oSpLCzpQyNHxsYTkEmYzvuq9YwW2es1JLJ/ymdluwQNDoR3a+2QD9nFKN0LzPw==]]: Update failed, RCODE = REFUSED
2022/06/02 14:12:55 VerifyDnskeysSynched: Fetching all ZSKs for msat1.catch22.se..

```

**Comment by johanix** [comment]
Why should it stop? 

To begin with, assume MUSIC is managing N zones and one of these zones have a problem of some sort (like the rcode=REFUSED above). Stopping would not be the right thing, as we still need to manage the remaining N-1 zones through their processes.

Secondly, in this case we have a signer that is "misconfigured", as it is rejecting the DDNS update. Then it would seem that the right approach would be to wait a bit and then try again, thereby allowing the misconfiguration to be fixed. And that's exactly what the code does. There's an exponential backoff that will keep trying, but less and less frequently. Isn't that the better alternative?

**Comment by romu42** [comment]
Not stop completely, but it seemed like it went on to the next state. I will retest and see if I can figure out the exact configuration that caused the bug.  

It would be helpful to have unit tests.

**Comment by johanix** [comment]
@romu42 will test further.

**Comment by romu42** [comment]
Tested and it seems to work as expected now. Closing this ticket.
