### ISSUE TITLE
We need a general function to compare two RRsets and return whether they are equal or not.

### ISSUE THREAD

**Issue by johanix** [DNSSEC-Provisioning/music#150]
Something like:

1. If different length --> fail
2. If different rrtype --> fail
3. If different owner --> fail
4. If different string.EqualFold(rdata) --> fail

else success.

**Comment by johanix** [comment]
Suggested interface:

func (rrs1 []*dns.RR) Compare (rrs2 []*dns.RR) (bool, []*dns.RR, []*dns.RR, error) 

- If equal => return (true, nil, nil, nil)
- If RR exists in rrs1 but not in rrs2 then list it in the second result
- If RR exists in rrs2 but not in rrs1 then list it in the third result
- If any kind of error is triggered return it in the fourth result

**Comment by romu42** [comment]
Implemented in #194. 
I have no idea to do it as an interface/receiver function. It is implemented as a function.
Tested it in join_add_cds and it seems to work as expected.
