### ISSUE TITLE
Need rewrite of DB layer

### ISSUE THREAD

**Issue by jelu** [DNSSEC-Provisioning/music#16]
- Remove `mdb.mu`, that lock does not protect anything
- Use transactions
- Don't issue `DELETE`'s when adding etc

**Comment by johanix** [comment]
This is still needed and important.

**Comment by johanix** [comment]
Another thing to consider is to implement SQLite WAL (Write Ahead Logging) as a trivial mechanism to avoid the dreaded "database is locked" errors that may happen with multiple simultaneous access (like more than one user only running manual).

**Comment by johanix** [comment]
I don't know if this is all done or not. I'm still confused over Malins comments in the pull request for branch issue16+api-changes.
