### ISSUE TITLE
Use cobra in a different way

### ISSUE THREAD

**Issue by jelu** [DNSSEC-Provisioning/music#18]
Right now most parameters to commands are flags, this is very counterintuitive.

Some flags are also global so it's very unclear in help text which are required from some commands and which are not.

- Rewrite and use cobra in a more normal command way that uses normal args for parameters, for example instead of `music-cli signer add -s signer-name -m method --address 1.2.3.4` all these flags are required and it should be `music-cli signer add signer-name method 1.2.3.4`
  - required parameters should be command line arguments
  - optional parameters should be flags

**Comment by johanix** [comment]
I have no strong feelings on this except that 
- I think what is considered "more normal" is in the eye of the beholder, I find flags more intuitive, you don't, that's ok
- one advantage of using flags is that order is irrelevant, when using (even) more sub commands thy must come in the right order or stuff fail.
- I don't know whether cobra easily supports the alternative semantics

**Comment by johanix** [comment]
I don't claim that it solves your issue completely, but it is possible to mark a flag as required and then leaving it out will trigger an error:

`processGraphCmd.Flags().StringVarP(&processname, "process", "p", "", "name of process")
processGraphCmd.MarkFlagRequired("process")`

**Comment by jelu** [comment]
> I don't claim that it solves your issue completely, but it is possible to mark a flag as required and then leaving it out will trigger an error:
> 
> `processGraphCmd.Flags().StringVarP(&processname, "process", "p", "", "name of process") processGraphCmd.MarkFlagRequired("process")`

That would be better then how it's done right now, see https://github.com/DNSSEC-Provisioning/music/blob/main/music-cli/cmd/signer.go#L33 .

**Comment by jelu** [comment]
>     * one advantage of using flags is that order is irrelevant, when using (even) more sub commands thy must come in the right order or stuff fail.

Problem is really that they are global flags, for example this help page is not helping at all:

```
$ ../sbin/music-cli zone step-fsm -h
Try to make the zone transition from one state to the next in the FSM

Usage:
  music-cli zone step-fsm [flags]

Flags:
  -h, --help               help for step-fsm
      --nextstate string   name of next state in on-going FSM process

Global Flags:
      --config string   config file (default is ../etc/music-cli.yaml)
  -d, --debug           Debugging output
  -g, --group string    name of signer group
  -s, --name string     name of signer
  -o, --owner string    DNS owner name of RRset
  -r, --rrtype string   RRtype of RRset
  -v, --verbose         Verbose output
  -z, --zone string     name of zone
```

There is no indication which of these global flags are relevant to the given command.
