### ISSUE TITLE
deSEC base URL required 

### ISSUE THREAD

**Issue by Chreo** [DNSSEC-Provisioning/music#215]
When performing a new setup of musicd it complains about missing deSEC base URL: 
`deSEC base URL configured as signers.desec.baseurl required`

It should certainly be possible to perform the setup without using provider X (deSEC inthis case), right?

**Comment by johanix** [comment]
Thanks, you're of course right. I have lost track of the deSEC "plugin", but assuming a future with more than one possible external provider perhaps a mandatory config could be a list of external plugins and then only do config validation for listed plugins.

Expect a fix "soonish", but possibly not until after the IETF.
