### ISSUE TITLE
Need FSM state metadata

### ISSUE THREAD

**Issue by jelu** [DNSSEC-Provisioning/music#34]
Need ways to store metadata for states in the database, for example in FsmJoinParentDsSynced all DNSKEYs in all signers are retrieved and the largest TTL is used to calculate DS wait time. This calculation should only be done once and the calculated time should be stored and checked against on next run.

**Comment by johanix** [comment]
In that particular case (and possibly in all cases) it is metadata per zone, so I suggest we store it in the DB in a separate key/value table for all zones, all keys. I.e.

 <$zone, "DS wait", value>

That way we will not have to change the DB schema every time we have a need for a new type of metadata.

**Comment by johanix** [comment]
This has been implemented.
