### ISSUE TITLE
Idea: Address the need to verify results from DNS lookups by using TSIG?

### ISSUE THREAD

**Issue by johanix** [DNSSEC-Provisioning/music#42]
I haven't tested this, but in theory TSIG should be able to secure any DNS transaction between two parties. 

So if we use that to secure the DNS queries where we fetch DNSKEYs, NS RRsets, etc, then we have something that is as strong as the security used for actually updating data. 

I.e. if we for some reason don't trust TSIG (which I think is stupid) then the entire DDNS method is flawed. And if we do trust TSIG, then we've solved the validation problem.

**Comment by romu42** [comment]
Notes from conversation with Johan:  

- Use TCP
- TSIG Sign Request
- Check Reply Signature

**Comment by johanix** [comment]
We do this now.
