### ISSUE TITLE
Add missing PreConditions and PostConditions to all states in all processes

### ISSUE THREAD

**Issue by johanix** [DNSSEC-Provisioning/music#68]

**Comment by johanix** [comment]
- [ ] *MUST* have complete set of post- and pre-conditions in final code.
- [ ] *MUST* sort out whether post-condition of Action N always equals pre-condition of Action N+1.

**Comment by romu42** [comment]
Should LeaveWaitNs should be the post condition to LeaveParentNsSynced?

**Comment by romu42** [comment]
1. Every Pre Condition -> Action -> Post Condition should be able to stand on its own.
2. With that said, if a Post Condition leads to a Pre Condition that does exactly the same thing then it should be via an external function/mechanism.
3. There are occurrences where the actions Creates a RRset and then the Post Condition checks the RRset, sometimes repeating the "create process" , Should we be saving the created RRsets and using those in the Post Condition as a praxis. This is not the case every where today.

**Comment by romu42** [comment]
- [ ] Go through join_sync_dnskeys.go code.
