### ISSUE TITLE
cli zone status cmd does Get Signer twice??

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#86]
CLI:
❯ mcli -H zone status -z msat1.catch22.se
Zone               SignerGroup  Process  State  Timestamp            Next State(s)  ZSK State
msat1.catch22.se.  msat1        ---      ---    2021-12-29 13:11:17  []             ---

MUSICD:
2022/01/10 10:59:44 APIzone: received /zone request (command: status) from 127.0.0.1:51022.
GGS: got signer name: signer1
GGS: got signer name: signer2
GGS: got signer name: signer1
GGS: got signer name: signer2

**Comment by johanix** [comment]
Should figure out what's happening here.

**Comment by romu42** [comment]
Cannot reproduce error..
