### ISSUE TITLE
What is status in the signers table used for?

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#88]
I am not sure what the status field in the signers table is used for.

"signers": `CREATE TABLE IF NOT EXISTS 'signers' (
id          INTEGER PRIMARY KEY,
name        TEXT,
method      TEXT,
auth        TEXT,
addr        TEXT,
port        TEXT,
status      TEXT,
UNIQUE (name)
)`,

**Comment by johanix** [comment]
Neither am I. My guess is that it is something I thought could come in useful, but hasn't yet.

**Comment by johanix** [comment]
Rip it out!
