### ISSUE TITLE
Need long and hard thinking through of join/leave logic

### ISSUE THREAD

**Issue by johanix** [DNSSEC-Provisioning/music#91]
- If a group is in a process (i.e. the zones are working their way through the process), can a new zone join the group?
- Can a zone leave the group (while the group is in a process), as long as the zone is done?
- If a zone joins a group and therefore initiates the add-signer process, does that cause the entire group to be locked (as it is no longer fully in sync)? If so it would take a very long time to add a significant number of zones to a group, so that's clearly not workable.

I **think** that my view is that we at least need to:

- Be able to add a bunch of zones w/o locking the group.
- Always be able to have a zone leave a group. Perhaps with a force flag, but it must always be possible to leave.
- It would not solve the problem to just associate the process entirely with the zone (instead of with the group), because we would still have the issue of a signer deciding to leave a group affecting a zone in that group where the zone was already busy with something else (perhaps it's initial ADD-SIGNER process).

Yet another approach could be to create a "process object" that contains all the details of what should be done, i.e. not only "remove signer", but "remove *this* signer", as an object. Then we could have a queue of process objects for each zone to work their way through.

**Comment by johanix** [comment]
More questions: let's assume that we have changed from having the current process only being a process name ("add-signer") and the name of the signer (pendingaddition=Signer3) in the SignerGroup structure, to instead be a CurProc{} struct installed in each zone.

- This makes the issue of "leavingSigner" etc, in the various FSM transitions much easier, because the name of the involved signer is available in the zone.
- But it makes the automatic insertion of new zones (zones that join the signer group) into the "add-signer" process difficult, because we don't really want to "add" a signer, we want to "check" whether the zone is in sync across all signers in the group. Or not. So add-signer is conceptually wrong. 
- Perhaps we need a new process, "check-signers"?
- Or should it be "add-signer" with a special signer name, like "all" or "*"?
-

**Comment by romu42** [comment]
> If a group is in a process (i.e. the zones are working their way through the process), can a new zone join the group?
NO. 
> Can a zone leave the group (while the group is in a process), as long as the zone is done?
NO.  Let us just keep it simpler and say no.

I think we should work with the assumption and the definition that a SignerGroup is a collection of signers and a collection of zones.
SignerGroup = [Signer1 ... SignerN] + [ Zone1 ... ZoneN] 

- Signers may be added to the SignerGroup.
- Signers may be removed from the SignerGroup as long as there will remain at least one Signer in the group.
- During the addition or removal of signers the zone collection may not change. 


In the case of adding zones to a SignerGroup there is nothing that will stop us from Creating a new SignerGroup with the same Signers that are already involved in other processes, we just create a new SignerGroup where the zone collection is the unique identifier.

I think "removing" zones from a SignerGroup before the SignerGroup transition is complete is adding unnecessary complexity at this juncture.
