### ISSUE TITLE
music-cli signer delete doesn't seem to work

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#93]
❯ mcli signer add -n bob -m ddns --address 1.1.1.1
New signer bob successfully added.

❯ mcli signer list
Signer   Method  Address       SignerGroups
bob      ddns    1.1.1.1       ---
signer1  ddns    13.53.206.47  msat1
signer2  ddns    13.53.34.31   msat1

❯ mcli signer delete bob
Signer  deleted.

❯ mcli signer list
Signer   Method  Address       SignerGroups
bob      ddns    1.1.1.1       ---
signer1  ddns    13.53.206.47  msat1
signer2  ddns    13.53.34.31   msat1

**Comment by romu42** [comment]
Delete works if you add the flags for name, method and address.  Bug or Feature?

❯ mcli signer list
Signer   Method  Address       SignerGroups
bob      ddns    1.1.1.1       ---
signer1  ddns    13.53.206.47  msat1
signer2  ddns    13.53.34.31   msat1

❯ mcli signer add -n bob -m ddns --address 1.1.1.1 -v
Using config file: ../etc/music-cli.yaml
Signer bob already present in system.

❯ mcli signer delete -n bob -m ddns --address 1.1.1.1 -v
Using config file: ../etc/music-cli.yaml
Signer bob deleted.

❯ mcli signer list
Signer   Method  Address       SignerGroups
signer1  ddns    13.53.206.47  msat1
signer2  ddns    13.53.34.31   msat1

**Comment by johanix** [comment]
WFM? I can delete a signer (as long as it isn't locked into a signer group) w/o giving the address, etc, details. Have you fixed this already?

**Comment by romu42** [comment]
I will test again and see how it works now with all the updates that have been implemented.

**Comment by romu42** [comment]
Tested and there was no problem to delete signer.
