### ISSUE TITLE
Need a state to represent that the zone in the signergroup is synced and in harmony

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#97]
When the signers and signergroup is all synced up we need a more explicit way to show this with the zone status cmd.

current output: 

```
❯ mcli zone status -z msat1.catch22.se
Zone               SignerGroup  Process  State  Timestamp            Next State(s)  ZSK State
msat1.catch22.se.  msat1        ---      ---    2022-01-25 08:49:51  []             ---
```

**Comment by johanix** [comment]
`
git/music/music-cli>../sbin/music-cli zone list -H             
Zone         SignerGroup  Process           State    Timestamp            Next State(s)  ZSK State
foo1.se.[D]  Group1       verify-zone-sync  stop     2022-01-27 21:15:39  []             ---
foo2.se.[D]  Group1       verify-zone-sync  stop     2022-01-27 21:15:39  []             ---
foo3.se.[D]  Group1       ---               IN-SYNC  2022-01-27 21:15:40  []             ---
foo4.se.[D]  Group1       verify-zone-sync  stop     2022-01-27 21:15:40  []             ---
foo5.se.[D]  Group1       verify-zone-sync  stop     2022-01-27 21:15:40  []             ---
`
Better?

**Comment by johanix** [comment]
Done.
